#!/usr/bin/env node
/**
 * build-site.mjs — rebuild `site/index.html` from `grammars/_eco_ids.json` + each grammar.json.
 * Pure node, no dependencies, no node_modules. Run it after adding or re-exporting a grammar.
 *
 *   node scripts/build-site.mjs
 *
 * The Pages workflow assembles the deploy directory (site/ + game/ + grammars/) itself; this
 * script only writes the index, which is committed so the repo shows what will be published.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ids = JSON.parse(readFileSync(join(ROOT, 'grammars', '_eco_ids.json'), 'utf8')).ids;

const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const firstLine = s => {
  const t = String(s ?? '').split('\n').find(l => l.trim()) || '';
  return t.length > 190 ? t.slice(0, 187).replace(/\s+\S*$/, '') + '…' : t;
};

const rows = [];
for (const [slug, id] of Object.entries(ids)) {
  const file = join(ROOT, 'grammars', slug, 'grammar.json');
  if (!existsSync(file)) { console.error(`  ! ${slug}: no grammar.json — skipped`); continue; }
  const g = JSON.parse(readFileSync(file, 'utf8'));
  rows.push({
    slug, id,
    name: g.name || slug,
    items: Array.isArray(g.items) ? g.items.length : 0,
    blurb: firstLine(g.description),
    type: g.grammar_type || '',
  });
}
rows.sort((a, b) => b.items - a.items);

const cards = rows.map(r => `      <li class="g">
        <a class="t" href="https://recursive.eco/view.html?id=${esc(r.id)}">${esc(r.name)}</a>
        <p class="b">${esc(r.blurb)}</p>
        <p class="m">${r.items} item${r.items === 1 ? '' : 's'}${r.type ? ' · ' + esc(r.type) : ''} ·
          <a href="grammars/${esc(r.slug)}/grammar.json">grammar.json</a> ·
          <a href="https://flow.recursive.eco/create/dashboard/unified/new?id=${esc(r.id)}">fork it</a></p>
      </li>`).join('\n');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Recursive Learning</title>
<!-- Generated by scripts/build-site.mjs — edit that, not this. -->
<style>
  :root{ --bg:#0d0f14; --panel:#151922; --line:#2a3140; --ink:#e8ecf3; --muted:#8e9aae; --accent:#5ee2b0; }
  *{box-sizing:border-box}
  html,body{margin:0;background:var(--bg);color:var(--ink);color-scheme:dark;
    font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;line-height:1.55}
  .wrap{max-width:820px;margin:0 auto;padding-block:30px 70px;padding-left:16px;padding-right:16px}
  a{color:var(--accent)}
  h1{font-size:26px;margin:0 0 10px}
  .thesis{font-size:15px;max-width:68ch;margin:0 0 14px}
  .note{color:var(--muted);font-size:13.5px;max-width:70ch;margin:0 0 26px}
  h2{font-size:13px;letter-spacing:.09em;text-transform:uppercase;color:var(--muted);
    margin:30px 0 12px;font-weight:600}
  .play{display:block;background:var(--panel);border:1px solid var(--line);border-left:3px solid var(--accent);
    border-radius:0 12px 12px 0;padding:15px 17px;text-decoration:none;color:var(--ink)}
  .play b{font-size:16px;color:var(--accent)} .play span{display:block;color:var(--muted);font-size:13.5px;margin-top:4px}
  ul{list-style:none;margin:0;padding:0;display:grid;gap:12px}
  .g{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px 16px}
  .g .t{font-size:16px;font-weight:700;text-decoration:none}
  .g .b{margin:6px 0 0;font-size:13.5px;color:var(--ink)}
  .g .m{margin:8px 0 0;font-size:12px;color:var(--muted)}
  footer{margin-top:34px;padding-top:14px;border-top:1px solid var(--line);color:var(--muted);font-size:12.5px}
</style>
</head>
<body>
<div class="wrap">
  <h1>Recursive Learning</h1>
  <p class="thesis">We're here to do recursive eco-improvement. Recursive self-improvement can fail
    in several ways, because a thing that improves itself still has to adapt <em>with</em> its
    environment, or adapt the environment. This is where that hypothesis gets tested at the sizes
    we actually work at.</p>
  <p class="note">One channel of <a href="https://recursive.eco">recursive.eco</a>, held in git:
    the film, the game, and the grammars about AI and about learning alongside it. Every grammar
    below can be opened, starred onto your own channel, forked, or corrected.</p>

  <h2>Play</h2>
  <a class="play" href="game/"><b>As-If — a recognition round</b>
    <span>Hold the premise as true and write what changes. The card only turns over once you have.</span></a>

  <h2>Grammars</h2>
  <ul>
${cards}
  </ul>

  <footer>PlayfulProcess · content CC BY-SA 4.0 ·
    <a href="https://github.com/PlayfulProcess/recursive-learning">the repo</a></footer>
</div>
</body>
</html>
`;

writeFileSync(join(ROOT, 'site', 'index.html'), html, 'utf8');
console.log(`site/index.html written — ${rows.length} grammars.`);
